/**
 * Evidence export routes — GET /evidence/:runId
 *
 * Returns the AEP evidence bundle embedded in a completed rollout record.
 * Supports JSON (default) and Markdown audit report formats.
 */
import type { Hono } from "hono";
import type { KvStore } from "../types.js";

export function registerEvidenceRoutes(app: Hono, kv?: KvStore): void {
  // GET /evidence/:runId — return AEP bundle as JSON
  app.get("/evidence/:runId", async (c) => {
    const runId = c.req.param("runId");
    // Try to load rollout record from KV (passed directly or via app config)
    const store: KvStore | undefined = kv;
    if (!store) {
      return c.json({ error: "storage unavailable" }, 503);
    }
    const raw = await store.get(`rollout:${runId}`).catch(() => null);
    if (!raw) {
      return c.json({ error: "run not found", run_id: runId }, 404);
    }
    let record: Record<string, unknown>;
    try {
      record = JSON.parse(raw);
    } catch {
      return c.json({ error: "malformed record" }, 500);
    }
    const aepEvidence = record.aep_evidence ?? null;
    if (!aepEvidence) {
      return c.json({
        run_id: runId,
        aep_evidence: null,
        message: "No AEP evidence recorded for this run",
      });
    }
    return c.json({
      run_id: runId,
      schema_version: "aep-bundle/v0.1",
      exported_at_ms: Date.now(),
      aep_evidence: aepEvidence,
      rollout_summary: {
        task: record.task,
        objective_status: record.objective_status,
        tool_call_count: Array.isArray(record.tool_call_sequence)
          ? record.tool_call_sequence.length
          : 0,
      },
    });
  });

  // GET /evidence/:runId/report — return markdown audit report
  app.get("/evidence/:runId/report", async (c) => {
    const runId = c.req.param("runId");
    const store: KvStore | undefined = kv;
    if (!store) {
      return c.text("# Error\n\nStorage unavailable.", 503);
    }
    const raw = await store.get(`rollout:${runId}`).catch(() => null);
    if (!raw) {
      return c.text(`# Evidence Report\n\nRun ${runId} not found.`, 404);
    }
    let record: Record<string, unknown>;
    try {
      record = JSON.parse(raw);
    } catch {
      return c.text("# Error\n\nMalformed record.", 500);
    }
    const aep = (record.aep_evidence as Record<string, unknown> | null) ?? {};
    const lines = [
      `# AEP Evidence Report — ${runId}`,
      "",
      `**Task:** ${record.task ?? "unknown"}`,
      `**Status:** ${record.objective_status ?? "unknown"}`,
      `**Exported:** ${new Date().toISOString()}`,
      "",
      "## Evidence Summary",
      "",
      `- schema_version: ${aep.schema_version ?? "n/a"}`,
      `- model_id: ${aep.model_id ?? "n/a"}`,
      `- tool_invocations: ${aep.tool_invocation_count ?? 0}`,
      `- capability_decisions: ${Array.isArray(aep.capability_decisions) ? aep.capability_decisions.length : 0}`,
      "",
      "## Policy Decisions",
      "",
    ];
    const decisions = (aep.capability_decisions as unknown[]) ?? [];
    if (decisions.length === 0) {
      lines.push("_No policy decisions recorded._");
    } else {
      for (const d of decisions as Record<string, unknown>[]) {
        const icon = d.decision === "allow" ? "+" : d.decision === "deny" ? "-" : "?";
        lines.push(
          `- [${icon}] ${d.capability} -> ${d.decision}${d.reason_code ? ` (${d.reason_code})` : ""}`
        );
      }
    }
    lines.push("", "---", "_Generated by bscode evidence export_");
    c.header("Content-Type", "text/markdown; charset=utf-8");
    return c.text(lines.join("\n"));
  });
}
